_wandb:
    value:
        cli_version: 0.22.1
        e:
            62bxr9qi4z61sjqjp0vuh64eofyprj2p:
                codePath: lab1/introduction.ipynb
                codePathLocal: introduction.ipynb
                email: kapiotrow@student.agh.edu.pl
                executable: /home/karolina/studia/gsn/venv/bin/python
                git:
                    remote: git@github.com:kapiotrow/gsn.git
                host: karolina-dell
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/karolina/studia/gsn/lab1/introduction.ipynb
                python: CPython 3.10.12
                root: /home/karolina/studia/gsn/lab1
                startedAt: "2025-10-06T18:00:28.883556Z"
                writerId: 62bxr9qi4z61sjqjp0vuh64eofyprj2p
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.10.12
            "5": 0.22.1
            "8":
                - 1
            "12": 0.22.1
            "13": linux-x86_64
